# Generated by Django 4.2.5 on 2023-10-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liked',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterField(
            model_name='liked',
            name='subtitle',
            field=models.TextField(verbose_name='Описаниее'),
        ),
    ]
