# Generated by Django 4.2.5 on 2023-10-07 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_alter_liked_options_alter_liked_subtitle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Liked',
        ),
    ]
