# Generated by Django 4.2.5 on 2023-10-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0006_genre_films_genre'),
        ('hello', '0004_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recs',
            options={'verbose_name': 'Рекомендация', 'verbose_name_plural': 'Рекомендация'},
        ),
        migrations.AlterField(
            model_name='recs',
            name='name',
            field=models.ManyToManyField(to='film.films', verbose_name='Рекомендованные'),
        ),
    ]
